-- CREATE TABLE `suborders` (
--   `id` int(10) NOT NULL,
--   `table_no` int(10) DEFAULT NULL,
--   `order_id` int(10) NOT NULL
--   `order_no` varchar(10) NOT NULL DEFAULT '0',
--   `suborder_no` varchar(10) NOT NULL DEFAULT '0',
--   `subtotal` float DEFAULT 0,
--   `discount_type` enum('UNKNOWN','FIXED','PERCENT') DEFAULT NULL,
--   `discount_value` float DEFAULT NULL,
--   `discount_amount` float DEFAULT NULL,
--   `tax` float DEFAULT NULL,
--   `tax_amount` float DEFAULT 0,
--   `total` float DEFAULT 0,
--   `paid_card` float DEFAULT 0,
--   `paid_cash` float DEFAULT 0,
--   `tip_card` float DEFAULT 0,
--   `tip_cash` float DEFAULT 0,
--   `change` float DEFAULT 0,
--   `created` datetime DEFAULT NULL,
--   `items` text
-- ) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- CREATE TABLE `suborder_items` (
--   `id` int(10) NOT NULL,
--   `suborder_id` int(10) NOT NULL,
--   `order_item_id` int(10) NOT NULL,
--   `name_en` varchar(100) DEFAULT NULL,
--   `name_xh` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
--   `state` enum('KEEP', 'SHARED', 'ASSIGN') DEFAULT 'KEEP',
--   `price` float DEFAULT 0,
--   `selected_extras` text,
--   `extras_amount` float DEFAULT 0,
--   `quantity` int(10) DEFAULT 1,
--   `shared_suborder` text,
--   `assigned_suborder` text
-- ) ENGINE=InnoDB DEFAULT CHARSET=latin1;